MIMYmlVersion: '0.1'
categories:
- Standard
mims:
- MIM0
- MIM1
- MIM2
- MIM3
description:
  en:
    features:
    - enables accessing data
    genericName: ''
    localisedName: OpenAPI 3.1
    longDescription: ''
    shortDescription: Standard for documenting LDT APIs so they are discoverable and
      interoperable.
developmentStatus: beta
landingURL: ''
repoURL: ''
legal:
  authorsFile:
  license: BSD-3-Clause
  mainCopyrightOwner: NEC
  repoOwner: ''
localisation:
  availableLanguages:
  - en
  localisationReady: false
maintenance:
  contacts:
  type: internal
name: OpenAPI 3.1
platforms:
- web
releaseDate:
roadmap:
softwareType: standalone/other
softwareVersion:
url:
usedBy:
